// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hero.proto

package yxl.day5.dto;

public final class HeroProto {
  private HeroProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeroOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Hero)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *攻击
     * </pre>
     *
     * <code>optional int64 attack = 1;</code>
     * @return Whether the attack field is set.
     */
    boolean hasAttack();
    /**
     * <pre>
     *攻击
     * </pre>
     *
     * <code>optional int64 attack = 1;</code>
     * @return The attack.
     */
    long getAttack();

    /**
     * <pre>
     *防御
     * </pre>
     *
     * <code>optional int64 defense = 2;</code>
     * @return Whether the defense field is set.
     */
    boolean hasDefense();
    /**
     * <pre>
     *防御
     * </pre>
     *
     * <code>optional int64 defense = 2;</code>
     * @return The defense.
     */
    long getDefense();

    /**
     * <pre>
     *生命值
     * </pre>
     *
     * <code>optional int64 life = 3;</code>
     * @return Whether the life field is set.
     */
    boolean hasLife();
    /**
     * <pre>
     *生命值
     * </pre>
     *
     * <code>optional int64 life = 3;</code>
     * @return The life.
     */
    long getLife();
  }
  /**
   * Protobuf type {@code Hero}
   */
  public static final class Hero extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Hero)
      HeroOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hero.newBuilder() to construct.
    private Hero(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hero() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Hero();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hero(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              attack_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              defense_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              life_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeroProto.internal_static_Hero_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeroProto.internal_static_Hero_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Hero.class, Builder.class);
    }

    private int bitField0_;
    public static final int ATTACK_FIELD_NUMBER = 1;
    private long attack_;
    /**
     * <pre>
     *攻击
     * </pre>
     *
     * <code>optional int64 attack = 1;</code>
     * @return Whether the attack field is set.
     */
    @Override
    public boolean hasAttack() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *攻击
     * </pre>
     *
     * <code>optional int64 attack = 1;</code>
     * @return The attack.
     */
    @Override
    public long getAttack() {
      return attack_;
    }

    public static final int DEFENSE_FIELD_NUMBER = 2;
    private long defense_;
    /**
     * <pre>
     *防御
     * </pre>
     *
     * <code>optional int64 defense = 2;</code>
     * @return Whether the defense field is set.
     */
    @Override
    public boolean hasDefense() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *防御
     * </pre>
     *
     * <code>optional int64 defense = 2;</code>
     * @return The defense.
     */
    @Override
    public long getDefense() {
      return defense_;
    }

    public static final int LIFE_FIELD_NUMBER = 3;
    private long life_;
    /**
     * <pre>
     *生命值
     * </pre>
     *
     * <code>optional int64 life = 3;</code>
     * @return Whether the life field is set.
     */
    @Override
    public boolean hasLife() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *生命值
     * </pre>
     *
     * <code>optional int64 life = 3;</code>
     * @return The life.
     */
    @Override
    public long getLife() {
      return life_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, attack_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, defense_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, life_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, attack_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, defense_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, life_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Hero)) {
        return super.equals(obj);
      }
      Hero other = (Hero) obj;

      if (hasAttack() != other.hasAttack()) return false;
      if (hasAttack()) {
        if (getAttack()
            != other.getAttack()) return false;
      }
      if (hasDefense() != other.hasDefense()) return false;
      if (hasDefense()) {
        if (getDefense()
            != other.getDefense()) return false;
      }
      if (hasLife() != other.hasLife()) return false;
      if (hasLife()) {
        if (getLife()
            != other.getLife()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAttack()) {
        hash = (37 * hash) + ATTACK_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAttack());
      }
      if (hasDefense()) {
        hash = (37 * hash) + DEFENSE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDefense());
      }
      if (hasLife()) {
        hash = (37 * hash) + LIFE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLife());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Hero parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Hero parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Hero parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Hero parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Hero parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Hero parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Hero parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Hero parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Hero parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Hero parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Hero parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Hero parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Hero prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Hero}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Hero)
        HeroOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeroProto.internal_static_Hero_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeroProto.internal_static_Hero_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Hero.class, Builder.class);
      }

      // Construct using yxl.day5.dto.HeroProto.Hero.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        attack_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        defense_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        life_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeroProto.internal_static_Hero_descriptor;
      }

      @Override
      public Hero getDefaultInstanceForType() {
        return Hero.getDefaultInstance();
      }

      @Override
      public Hero build() {
        Hero result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Hero buildPartial() {
        Hero result = new Hero(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.attack_ = attack_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.defense_ = defense_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.life_ = life_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Hero) {
          return mergeFrom((Hero)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Hero other) {
        if (other == Hero.getDefaultInstance()) return this;
        if (other.hasAttack()) {
          setAttack(other.getAttack());
        }
        if (other.hasDefense()) {
          setDefense(other.getDefense());
        }
        if (other.hasLife()) {
          setLife(other.getLife());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Hero parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Hero) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long attack_ ;
      /**
       * <pre>
       *攻击
       * </pre>
       *
       * <code>optional int64 attack = 1;</code>
       * @return Whether the attack field is set.
       */
      @Override
      public boolean hasAttack() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *攻击
       * </pre>
       *
       * <code>optional int64 attack = 1;</code>
       * @return The attack.
       */
      @Override
      public long getAttack() {
        return attack_;
      }
      /**
       * <pre>
       *攻击
       * </pre>
       *
       * <code>optional int64 attack = 1;</code>
       * @param value The attack to set.
       * @return This builder for chaining.
       */
      public Builder setAttack(long value) {
        bitField0_ |= 0x00000001;
        attack_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *攻击
       * </pre>
       *
       * <code>optional int64 attack = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttack() {
        bitField0_ = (bitField0_ & ~0x00000001);
        attack_ = 0L;
        onChanged();
        return this;
      }

      private long defense_ ;
      /**
       * <pre>
       *防御
       * </pre>
       *
       * <code>optional int64 defense = 2;</code>
       * @return Whether the defense field is set.
       */
      @Override
      public boolean hasDefense() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *防御
       * </pre>
       *
       * <code>optional int64 defense = 2;</code>
       * @return The defense.
       */
      @Override
      public long getDefense() {
        return defense_;
      }
      /**
       * <pre>
       *防御
       * </pre>
       *
       * <code>optional int64 defense = 2;</code>
       * @param value The defense to set.
       * @return This builder for chaining.
       */
      public Builder setDefense(long value) {
        bitField0_ |= 0x00000002;
        defense_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *防御
       * </pre>
       *
       * <code>optional int64 defense = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDefense() {
        bitField0_ = (bitField0_ & ~0x00000002);
        defense_ = 0L;
        onChanged();
        return this;
      }

      private long life_ ;
      /**
       * <pre>
       *生命值
       * </pre>
       *
       * <code>optional int64 life = 3;</code>
       * @return Whether the life field is set.
       */
      @Override
      public boolean hasLife() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *生命值
       * </pre>
       *
       * <code>optional int64 life = 3;</code>
       * @return The life.
       */
      @Override
      public long getLife() {
        return life_;
      }
      /**
       * <pre>
       *生命值
       * </pre>
       *
       * <code>optional int64 life = 3;</code>
       * @param value The life to set.
       * @return This builder for chaining.
       */
      public Builder setLife(long value) {
        bitField0_ |= 0x00000004;
        life_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *生命值
       * </pre>
       *
       * <code>optional int64 life = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLife() {
        bitField0_ = (bitField0_ & ~0x00000004);
        life_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Hero)
    }

    // @@protoc_insertion_point(class_scope:Hero)
    private static final Hero DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Hero();
    }

    public static Hero getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hero>
        PARSER = new com.google.protobuf.AbstractParser<Hero>() {
      @Override
      public Hero parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hero(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hero> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Hero> getParserForType() {
      return PARSER;
    }

    @Override
    public Hero getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Role)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 id = 1;</code>
     * @return A list containing the id.
     */
    java.util.List<Integer> getIdList();
    /**
     * <code>repeated int32 id = 1;</code>
     * @return The count of id.
     */
    int getIdCount();
    /**
     * <code>repeated int32 id = 1;</code>
     * @param index The index of the element to return.
     * @return The id at the given index.
     */
    int getId(int index);

    /**
     * <code>repeated int32 uid = 2;</code>
     * @return A list containing the uid.
     */
    java.util.List<Integer> getUidList();
    /**
     * <code>repeated int32 uid = 2;</code>
     * @return The count of uid.
     */
    int getUidCount();
    /**
     * <code>repeated int32 uid = 2;</code>
     * @param index The index of the element to return.
     * @return The uid at the given index.
     */
    int getUid(int index);

    /**
     * <code>repeated int32 serverId = 3;</code>
     * @return A list containing the serverId.
     */
    java.util.List<Integer> getServerIdList();
    /**
     * <code>repeated int32 serverId = 3;</code>
     * @return The count of serverId.
     */
    int getServerIdCount();
    /**
     * <code>repeated int32 serverId = 3;</code>
     * @param index The index of the element to return.
     * @return The serverId at the given index.
     */
    int getServerId(int index);

    /**
     * <code>repeated int32 roleId = 4;</code>
     * @return A list containing the roleId.
     */
    java.util.List<Integer> getRoleIdList();
    /**
     * <code>repeated int32 roleId = 4;</code>
     * @return The count of roleId.
     */
    int getRoleIdCount();
    /**
     * <code>repeated int32 roleId = 4;</code>
     * @param index The index of the element to return.
     * @return The roleId at the given index.
     */
    int getRoleId(int index);

    /**
     * <code>repeated string roleName = 5;</code>
     * @return A list containing the roleName.
     */
    java.util.List<String>
        getRoleNameList();
    /**
     * <code>repeated string roleName = 5;</code>
     * @return The count of roleName.
     */
    int getRoleNameCount();
    /**
     * <code>repeated string roleName = 5;</code>
     * @param index The index of the element to return.
     * @return The roleName at the given index.
     */
    String getRoleName(int index);
    /**
     * <code>repeated string roleName = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the roleName at the given index.
     */
    com.google.protobuf.ByteString
        getRoleNameBytes(int index);

    /**
     * <code>repeated string roleType = 6;</code>
     * @return A list containing the roleType.
     */
    java.util.List<String>
        getRoleTypeList();
    /**
     * <code>repeated string roleType = 6;</code>
     * @return The count of roleType.
     */
    int getRoleTypeCount();
    /**
     * <code>repeated string roleType = 6;</code>
     * @param index The index of the element to return.
     * @return The roleType at the given index.
     */
    String getRoleType(int index);
    /**
     * <code>repeated string roleType = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the roleType at the given index.
     */
    com.google.protobuf.ByteString
        getRoleTypeBytes(int index);

    /**
     * <code>repeated .Hero hero = 7;</code>
     */
    java.util.List<Hero>
        getHeroList();
    /**
     * <code>repeated .Hero hero = 7;</code>
     */
    Hero getHero(int index);
    /**
     * <code>repeated .Hero hero = 7;</code>
     */
    int getHeroCount();
    /**
     * <code>repeated .Hero hero = 7;</code>
     */
    java.util.List<? extends HeroOrBuilder>
        getHeroOrBuilderList();
    /**
     * <code>repeated .Hero hero = 7;</code>
     */
    HeroOrBuilder getHeroOrBuilder(
        int index);

    /**
     * <code>repeated int32 heroLen = 8;</code>
     * @return A list containing the heroLen.
     */
    java.util.List<Integer> getHeroLenList();
    /**
     * <code>repeated int32 heroLen = 8;</code>
     * @return The count of heroLen.
     */
    int getHeroLenCount();
    /**
     * <code>repeated int32 heroLen = 8;</code>
     * @param index The index of the element to return.
     * @return The heroLen at the given index.
     */
    int getHeroLen(int index);

    /**
     * <code>optional string message = 9;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 9;</code>
     * @return The message.
     */
    String getMessage();
    /**
     * <code>optional string message = 9;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code Role}
   */
  public static final class Role extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Role)
      RoleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Role.newBuilder() to construct.
    private Role(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Role() {
      id_ = emptyIntList();
      uid_ = emptyIntList();
      serverId_ = emptyIntList();
      roleId_ = emptyIntList();
      roleName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      roleType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      hero_ = java.util.Collections.emptyList();
      heroLen_ = emptyIntList();
      message_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Role();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Role(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                id_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              id_.addInt(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                id_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                id_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                uid_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              uid_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                uid_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                uid_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                serverId_ = newIntList();
                mutable_bitField0_ |= 0x00000004;
              }
              serverId_.addInt(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
                serverId_ = newIntList();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                serverId_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                roleId_ = newIntList();
                mutable_bitField0_ |= 0x00000008;
              }
              roleId_.addInt(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) != 0) && input.getBytesUntilLimit() > 0) {
                roleId_ = newIntList();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                roleId_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                roleName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              roleName_.add(s);
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                roleType_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              roleType_.add(s);
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) != 0)) {
                hero_ = new java.util.ArrayList<Hero>();
                mutable_bitField0_ |= 0x00000040;
              }
              hero_.add(
                  input.readMessage(Hero.parser(), extensionRegistry));
              break;
            }
            case 64: {
              if (!((mutable_bitField0_ & 0x00000080) != 0)) {
                heroLen_ = newIntList();
                mutable_bitField0_ |= 0x00000080;
              }
              heroLen_.addInt(input.readInt32());
              break;
            }
            case 66: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000080) != 0) && input.getBytesUntilLimit() > 0) {
                heroLen_ = newIntList();
                mutable_bitField0_ |= 0x00000080;
              }
              while (input.getBytesUntilLimit() > 0) {
                heroLen_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          id_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          uid_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          serverId_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          roleId_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          roleName_ = roleName_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000020) != 0)) {
          roleType_ = roleType_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000040) != 0)) {
          hero_ = java.util.Collections.unmodifiableList(hero_);
        }
        if (((mutable_bitField0_ & 0x00000080) != 0)) {
          heroLen_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeroProto.internal_static_Role_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeroProto.internal_static_Role_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Role.class, Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList id_;
    /**
     * <code>repeated int32 id = 1;</code>
     * @return A list containing the id.
     */
    @Override
    public java.util.List<Integer>
        getIdList() {
      return id_;
    }
    /**
     * <code>repeated int32 id = 1;</code>
     * @return The count of id.
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated int32 id = 1;</code>
     * @param index The index of the element to return.
     * @return The id at the given index.
     */
    public int getId(int index) {
      return id_.getInt(index);
    }
    private int idMemoizedSerializedSize = -1;

    public static final int UID_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList uid_;
    /**
     * <code>repeated int32 uid = 2;</code>
     * @return A list containing the uid.
     */
    @Override
    public java.util.List<Integer>
        getUidList() {
      return uid_;
    }
    /**
     * <code>repeated int32 uid = 2;</code>
     * @return The count of uid.
     */
    public int getUidCount() {
      return uid_.size();
    }
    /**
     * <code>repeated int32 uid = 2;</code>
     * @param index The index of the element to return.
     * @return The uid at the given index.
     */
    public int getUid(int index) {
      return uid_.getInt(index);
    }
    private int uidMemoizedSerializedSize = -1;

    public static final int SERVERID_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.IntList serverId_;
    /**
     * <code>repeated int32 serverId = 3;</code>
     * @return A list containing the serverId.
     */
    @Override
    public java.util.List<Integer>
        getServerIdList() {
      return serverId_;
    }
    /**
     * <code>repeated int32 serverId = 3;</code>
     * @return The count of serverId.
     */
    public int getServerIdCount() {
      return serverId_.size();
    }
    /**
     * <code>repeated int32 serverId = 3;</code>
     * @param index The index of the element to return.
     * @return The serverId at the given index.
     */
    public int getServerId(int index) {
      return serverId_.getInt(index);
    }
    private int serverIdMemoizedSerializedSize = -1;

    public static final int ROLEID_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.IntList roleId_;
    /**
     * <code>repeated int32 roleId = 4;</code>
     * @return A list containing the roleId.
     */
    @Override
    public java.util.List<Integer>
        getRoleIdList() {
      return roleId_;
    }
    /**
     * <code>repeated int32 roleId = 4;</code>
     * @return The count of roleId.
     */
    public int getRoleIdCount() {
      return roleId_.size();
    }
    /**
     * <code>repeated int32 roleId = 4;</code>
     * @param index The index of the element to return.
     * @return The roleId at the given index.
     */
    public int getRoleId(int index) {
      return roleId_.getInt(index);
    }
    private int roleIdMemoizedSerializedSize = -1;

    public static final int ROLENAME_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList roleName_;
    /**
     * <code>repeated string roleName = 5;</code>
     * @return A list containing the roleName.
     */
    public com.google.protobuf.ProtocolStringList
        getRoleNameList() {
      return roleName_;
    }
    /**
     * <code>repeated string roleName = 5;</code>
     * @return The count of roleName.
     */
    public int getRoleNameCount() {
      return roleName_.size();
    }
    /**
     * <code>repeated string roleName = 5;</code>
     * @param index The index of the element to return.
     * @return The roleName at the given index.
     */
    public String getRoleName(int index) {
      return roleName_.get(index);
    }
    /**
     * <code>repeated string roleName = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the roleName at the given index.
     */
    public com.google.protobuf.ByteString
        getRoleNameBytes(int index) {
      return roleName_.getByteString(index);
    }

    public static final int ROLETYPE_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList roleType_;
    /**
     * <code>repeated string roleType = 6;</code>
     * @return A list containing the roleType.
     */
    public com.google.protobuf.ProtocolStringList
        getRoleTypeList() {
      return roleType_;
    }
    /**
     * <code>repeated string roleType = 6;</code>
     * @return The count of roleType.
     */
    public int getRoleTypeCount() {
      return roleType_.size();
    }
    /**
     * <code>repeated string roleType = 6;</code>
     * @param index The index of the element to return.
     * @return The roleType at the given index.
     */
    public String getRoleType(int index) {
      return roleType_.get(index);
    }
    /**
     * <code>repeated string roleType = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the roleType at the given index.
     */
    public com.google.protobuf.ByteString
        getRoleTypeBytes(int index) {
      return roleType_.getByteString(index);
    }

    public static final int HERO_FIELD_NUMBER = 7;
    private java.util.List<Hero> hero_;
    /**
     * <code>repeated .Hero hero = 7;</code>
     */
    @Override
    public java.util.List<Hero> getHeroList() {
      return hero_;
    }
    /**
     * <code>repeated .Hero hero = 7;</code>
     */
    @Override
    public java.util.List<? extends HeroOrBuilder>
        getHeroOrBuilderList() {
      return hero_;
    }
    /**
     * <code>repeated .Hero hero = 7;</code>
     */
    @Override
    public int getHeroCount() {
      return hero_.size();
    }
    /**
     * <code>repeated .Hero hero = 7;</code>
     */
    @Override
    public Hero getHero(int index) {
      return hero_.get(index);
    }
    /**
     * <code>repeated .Hero hero = 7;</code>
     */
    @Override
    public HeroOrBuilder getHeroOrBuilder(
        int index) {
      return hero_.get(index);
    }

    public static final int HEROLEN_FIELD_NUMBER = 8;
    private com.google.protobuf.Internal.IntList heroLen_;
    /**
     * <code>repeated int32 heroLen = 8;</code>
     * @return A list containing the heroLen.
     */
    @Override
    public java.util.List<Integer>
        getHeroLenList() {
      return heroLen_;
    }
    /**
     * <code>repeated int32 heroLen = 8;</code>
     * @return The count of heroLen.
     */
    public int getHeroLenCount() {
      return heroLen_.size();
    }
    /**
     * <code>repeated int32 heroLen = 8;</code>
     * @param index The index of the element to return.
     * @return The heroLen at the given index.
     */
    public int getHeroLen(int index) {
      return heroLen_.getInt(index);
    }
    private int heroLenMemoizedSerializedSize = -1;

    public static final int MESSAGE_FIELD_NUMBER = 9;
    private volatile Object message_;
    /**
     * <code>optional string message = 9;</code>
     * @return Whether the message field is set.
     */
    @Override
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string message = 9;</code>
     * @return The message.
     */
    @Override
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>optional string message = 9;</code>
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getIdList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(idMemoizedSerializedSize);
      }
      for (int i = 0; i < id_.size(); i++) {
        output.writeInt32NoTag(id_.getInt(i));
      }
      if (getUidList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(uidMemoizedSerializedSize);
      }
      for (int i = 0; i < uid_.size(); i++) {
        output.writeInt32NoTag(uid_.getInt(i));
      }
      if (getServerIdList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(serverIdMemoizedSerializedSize);
      }
      for (int i = 0; i < serverId_.size(); i++) {
        output.writeInt32NoTag(serverId_.getInt(i));
      }
      if (getRoleIdList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(roleIdMemoizedSerializedSize);
      }
      for (int i = 0; i < roleId_.size(); i++) {
        output.writeInt32NoTag(roleId_.getInt(i));
      }
      for (int i = 0; i < roleName_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, roleName_.getRaw(i));
      }
      for (int i = 0; i < roleType_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, roleType_.getRaw(i));
      }
      for (int i = 0; i < hero_.size(); i++) {
        output.writeMessage(7, hero_.get(i));
      }
      if (getHeroLenList().size() > 0) {
        output.writeUInt32NoTag(66);
        output.writeUInt32NoTag(heroLenMemoizedSerializedSize);
      }
      for (int i = 0; i < heroLen_.size(); i++) {
        output.writeInt32NoTag(heroLen_.getInt(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, message_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < id_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(id_.getInt(i));
        }
        size += dataSize;
        if (!getIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        idMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < uid_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(uid_.getInt(i));
        }
        size += dataSize;
        if (!getUidList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        uidMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < serverId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(serverId_.getInt(i));
        }
        size += dataSize;
        if (!getServerIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        serverIdMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < roleId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(roleId_.getInt(i));
        }
        size += dataSize;
        if (!getRoleIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        roleIdMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < roleName_.size(); i++) {
          dataSize += computeStringSizeNoTag(roleName_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRoleNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < roleType_.size(); i++) {
          dataSize += computeStringSizeNoTag(roleType_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRoleTypeList().size();
      }
      for (int i = 0; i < hero_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, hero_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < heroLen_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(heroLen_.getInt(i));
        }
        size += dataSize;
        if (!getHeroLenList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        heroLenMemoizedSerializedSize = dataSize;
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Role)) {
        return super.equals(obj);
      }
      Role other = (Role) obj;

      if (!getIdList()
          .equals(other.getIdList())) return false;
      if (!getUidList()
          .equals(other.getUidList())) return false;
      if (!getServerIdList()
          .equals(other.getServerIdList())) return false;
      if (!getRoleIdList()
          .equals(other.getRoleIdList())) return false;
      if (!getRoleNameList()
          .equals(other.getRoleNameList())) return false;
      if (!getRoleTypeList()
          .equals(other.getRoleTypeList())) return false;
      if (!getHeroList()
          .equals(other.getHeroList())) return false;
      if (!getHeroLenList()
          .equals(other.getHeroLenList())) return false;
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIdCount() > 0) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getIdList().hashCode();
      }
      if (getUidCount() > 0) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUidList().hashCode();
      }
      if (getServerIdCount() > 0) {
        hash = (37 * hash) + SERVERID_FIELD_NUMBER;
        hash = (53 * hash) + getServerIdList().hashCode();
      }
      if (getRoleIdCount() > 0) {
        hash = (37 * hash) + ROLEID_FIELD_NUMBER;
        hash = (53 * hash) + getRoleIdList().hashCode();
      }
      if (getRoleNameCount() > 0) {
        hash = (37 * hash) + ROLENAME_FIELD_NUMBER;
        hash = (53 * hash) + getRoleNameList().hashCode();
      }
      if (getRoleTypeCount() > 0) {
        hash = (37 * hash) + ROLETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getRoleTypeList().hashCode();
      }
      if (getHeroCount() > 0) {
        hash = (37 * hash) + HERO_FIELD_NUMBER;
        hash = (53 * hash) + getHeroList().hashCode();
      }
      if (getHeroLenCount() > 0) {
        hash = (37 * hash) + HEROLEN_FIELD_NUMBER;
        hash = (53 * hash) + getHeroLenList().hashCode();
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Role parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Role parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Role parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Role parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Role parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Role parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Role parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Role parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Role parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Role parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Role parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Role parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Role prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Role}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Role)
        RoleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeroProto.internal_static_Role_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeroProto.internal_static_Role_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Role.class, Builder.class);
      }

      // Construct using yxl.day5.dto.HeroProto.Role.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeroFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        serverId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        roleId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        roleName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        roleType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (heroBuilder_ == null) {
          hero_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          heroBuilder_.clear();
        }
        heroLen_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000080);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeroProto.internal_static_Role_descriptor;
      }

      @Override
      public Role getDefaultInstanceForType() {
        return Role.getDefaultInstance();
      }

      @Override
      public Role build() {
        Role result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Role buildPartial() {
        Role result = new Role(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          id_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) != 0)) {
          uid_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.uid_ = uid_;
        if (((bitField0_ & 0x00000004) != 0)) {
          serverId_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.serverId_ = serverId_;
        if (((bitField0_ & 0x00000008) != 0)) {
          roleId_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.roleId_ = roleId_;
        if (((bitField0_ & 0x00000010) != 0)) {
          roleName_ = roleName_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.roleName_ = roleName_;
        if (((bitField0_ & 0x00000020) != 0)) {
          roleType_ = roleType_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.roleType_ = roleType_;
        if (heroBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0)) {
            hero_ = java.util.Collections.unmodifiableList(hero_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.hero_ = hero_;
        } else {
          result.hero_ = heroBuilder_.build();
        }
        if (((bitField0_ & 0x00000080) != 0)) {
          heroLen_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.heroLen_ = heroLen_;
        if (((from_bitField0_ & 0x00000100) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Role) {
          return mergeFrom((Role)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Role other) {
        if (other == Role.getDefaultInstance()) return this;
        if (!other.id_.isEmpty()) {
          if (id_.isEmpty()) {
            id_ = other.id_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdIsMutable();
            id_.addAll(other.id_);
          }
          onChanged();
        }
        if (!other.uid_.isEmpty()) {
          if (uid_.isEmpty()) {
            uid_ = other.uid_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUidIsMutable();
            uid_.addAll(other.uid_);
          }
          onChanged();
        }
        if (!other.serverId_.isEmpty()) {
          if (serverId_.isEmpty()) {
            serverId_ = other.serverId_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureServerIdIsMutable();
            serverId_.addAll(other.serverId_);
          }
          onChanged();
        }
        if (!other.roleId_.isEmpty()) {
          if (roleId_.isEmpty()) {
            roleId_ = other.roleId_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureRoleIdIsMutable();
            roleId_.addAll(other.roleId_);
          }
          onChanged();
        }
        if (!other.roleName_.isEmpty()) {
          if (roleName_.isEmpty()) {
            roleName_ = other.roleName_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureRoleNameIsMutable();
            roleName_.addAll(other.roleName_);
          }
          onChanged();
        }
        if (!other.roleType_.isEmpty()) {
          if (roleType_.isEmpty()) {
            roleType_ = other.roleType_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureRoleTypeIsMutable();
            roleType_.addAll(other.roleType_);
          }
          onChanged();
        }
        if (heroBuilder_ == null) {
          if (!other.hero_.isEmpty()) {
            if (hero_.isEmpty()) {
              hero_ = other.hero_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureHeroIsMutable();
              hero_.addAll(other.hero_);
            }
            onChanged();
          }
        } else {
          if (!other.hero_.isEmpty()) {
            if (heroBuilder_.isEmpty()) {
              heroBuilder_.dispose();
              heroBuilder_ = null;
              hero_ = other.hero_;
              bitField0_ = (bitField0_ & ~0x00000040);
              heroBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHeroFieldBuilder() : null;
            } else {
              heroBuilder_.addAllMessages(other.hero_);
            }
          }
        }
        if (!other.heroLen_.isEmpty()) {
          if (heroLen_.isEmpty()) {
            heroLen_ = other.heroLen_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureHeroLenIsMutable();
            heroLen_.addAll(other.heroLen_);
          }
          onChanged();
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000100;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Role parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Role) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList id_ = emptyIntList();
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          id_ = mutableCopy(id_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 id = 1;</code>
       * @return A list containing the id.
       */
      public java.util.List<Integer>
          getIdList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(id_) : id_;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       * @return The count of id.
       */
      public int getIdCount() {
        return id_.size();
      }
      /**
       * <code>repeated int32 id = 1;</code>
       * @param index The index of the element to return.
       * @return The id at the given index.
       */
      public int getId(int index) {
        return id_.getInt(index);
      }
      /**
       * <code>repeated int32 id = 1;</code>
       * @param index The index to set the value at.
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          int index, int value) {
        ensureIdIsMutable();
        id_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       * @param value The id to add.
       * @return This builder for chaining.
       */
      public Builder addId(int value) {
        ensureIdIsMutable();
        id_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       * @param values The id to add.
       * @return This builder for chaining.
       */
      public Builder addAllId(
          Iterable<? extends Integer> values) {
        ensureIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, id_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList uid_ = emptyIntList();
      private void ensureUidIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          uid_ = mutableCopy(uid_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 uid = 2;</code>
       * @return A list containing the uid.
       */
      public java.util.List<Integer>
          getUidList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(uid_) : uid_;
      }
      /**
       * <code>repeated int32 uid = 2;</code>
       * @return The count of uid.
       */
      public int getUidCount() {
        return uid_.size();
      }
      /**
       * <code>repeated int32 uid = 2;</code>
       * @param index The index of the element to return.
       * @return The uid at the given index.
       */
      public int getUid(int index) {
        return uid_.getInt(index);
      }
      /**
       * <code>repeated int32 uid = 2;</code>
       * @param index The index to set the value at.
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(
          int index, int value) {
        ensureUidIsMutable();
        uid_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 uid = 2;</code>
       * @param value The uid to add.
       * @return This builder for chaining.
       */
      public Builder addUid(int value) {
        ensureUidIsMutable();
        uid_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 uid = 2;</code>
       * @param values The uid to add.
       * @return This builder for chaining.
       */
      public Builder addAllUid(
          Iterable<? extends Integer> values) {
        ensureUidIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, uid_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 uid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        uid_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList serverId_ = emptyIntList();
      private void ensureServerIdIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          serverId_ = mutableCopy(serverId_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 serverId = 3;</code>
       * @return A list containing the serverId.
       */
      public java.util.List<Integer>
          getServerIdList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(serverId_) : serverId_;
      }
      /**
       * <code>repeated int32 serverId = 3;</code>
       * @return The count of serverId.
       */
      public int getServerIdCount() {
        return serverId_.size();
      }
      /**
       * <code>repeated int32 serverId = 3;</code>
       * @param index The index of the element to return.
       * @return The serverId at the given index.
       */
      public int getServerId(int index) {
        return serverId_.getInt(index);
      }
      /**
       * <code>repeated int32 serverId = 3;</code>
       * @param index The index to set the value at.
       * @param value The serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerId(
          int index, int value) {
        ensureServerIdIsMutable();
        serverId_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 serverId = 3;</code>
       * @param value The serverId to add.
       * @return This builder for chaining.
       */
      public Builder addServerId(int value) {
        ensureServerIdIsMutable();
        serverId_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 serverId = 3;</code>
       * @param values The serverId to add.
       * @return This builder for chaining.
       */
      public Builder addAllServerId(
          Iterable<? extends Integer> values) {
        ensureServerIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, serverId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 serverId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerId() {
        serverId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList roleId_ = emptyIntList();
      private void ensureRoleIdIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          roleId_ = mutableCopy(roleId_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 roleId = 4;</code>
       * @return A list containing the roleId.
       */
      public java.util.List<Integer>
          getRoleIdList() {
        return ((bitField0_ & 0x00000008) != 0) ?
                 java.util.Collections.unmodifiableList(roleId_) : roleId_;
      }
      /**
       * <code>repeated int32 roleId = 4;</code>
       * @return The count of roleId.
       */
      public int getRoleIdCount() {
        return roleId_.size();
      }
      /**
       * <code>repeated int32 roleId = 4;</code>
       * @param index The index of the element to return.
       * @return The roleId at the given index.
       */
      public int getRoleId(int index) {
        return roleId_.getInt(index);
      }
      /**
       * <code>repeated int32 roleId = 4;</code>
       * @param index The index to set the value at.
       * @param value The roleId to set.
       * @return This builder for chaining.
       */
      public Builder setRoleId(
          int index, int value) {
        ensureRoleIdIsMutable();
        roleId_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 roleId = 4;</code>
       * @param value The roleId to add.
       * @return This builder for chaining.
       */
      public Builder addRoleId(int value) {
        ensureRoleIdIsMutable();
        roleId_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 roleId = 4;</code>
       * @param values The roleId to add.
       * @return This builder for chaining.
       */
      public Builder addAllRoleId(
          Iterable<? extends Integer> values) {
        ensureRoleIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roleId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 roleId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoleId() {
        roleId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList roleName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRoleNameIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          roleName_ = new com.google.protobuf.LazyStringArrayList(roleName_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string roleName = 5;</code>
       * @return A list containing the roleName.
       */
      public com.google.protobuf.ProtocolStringList
          getRoleNameList() {
        return roleName_.getUnmodifiableView();
      }
      /**
       * <code>repeated string roleName = 5;</code>
       * @return The count of roleName.
       */
      public int getRoleNameCount() {
        return roleName_.size();
      }
      /**
       * <code>repeated string roleName = 5;</code>
       * @param index The index of the element to return.
       * @return The roleName at the given index.
       */
      public String getRoleName(int index) {
        return roleName_.get(index);
      }
      /**
       * <code>repeated string roleName = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the roleName at the given index.
       */
      public com.google.protobuf.ByteString
          getRoleNameBytes(int index) {
        return roleName_.getByteString(index);
      }
      /**
       * <code>repeated string roleName = 5;</code>
       * @param index The index to set the value at.
       * @param value The roleName to set.
       * @return This builder for chaining.
       */
      public Builder setRoleName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRoleNameIsMutable();
        roleName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roleName = 5;</code>
       * @param value The roleName to add.
       * @return This builder for chaining.
       */
      public Builder addRoleName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRoleNameIsMutable();
        roleName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roleName = 5;</code>
       * @param values The roleName to add.
       * @return This builder for chaining.
       */
      public Builder addAllRoleName(
          Iterable<String> values) {
        ensureRoleNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roleName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roleName = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoleName() {
        roleName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roleName = 5;</code>
       * @param value The bytes of the roleName to add.
       * @return This builder for chaining.
       */
      public Builder addRoleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRoleNameIsMutable();
        roleName_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList roleType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRoleTypeIsMutable() {
        if (!((bitField0_ & 0x00000020) != 0)) {
          roleType_ = new com.google.protobuf.LazyStringArrayList(roleType_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string roleType = 6;</code>
       * @return A list containing the roleType.
       */
      public com.google.protobuf.ProtocolStringList
          getRoleTypeList() {
        return roleType_.getUnmodifiableView();
      }
      /**
       * <code>repeated string roleType = 6;</code>
       * @return The count of roleType.
       */
      public int getRoleTypeCount() {
        return roleType_.size();
      }
      /**
       * <code>repeated string roleType = 6;</code>
       * @param index The index of the element to return.
       * @return The roleType at the given index.
       */
      public String getRoleType(int index) {
        return roleType_.get(index);
      }
      /**
       * <code>repeated string roleType = 6;</code>
       * @param index The index of the value to return.
       * @return The bytes of the roleType at the given index.
       */
      public com.google.protobuf.ByteString
          getRoleTypeBytes(int index) {
        return roleType_.getByteString(index);
      }
      /**
       * <code>repeated string roleType = 6;</code>
       * @param index The index to set the value at.
       * @param value The roleType to set.
       * @return This builder for chaining.
       */
      public Builder setRoleType(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRoleTypeIsMutable();
        roleType_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roleType = 6;</code>
       * @param value The roleType to add.
       * @return This builder for chaining.
       */
      public Builder addRoleType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRoleTypeIsMutable();
        roleType_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roleType = 6;</code>
       * @param values The roleType to add.
       * @return This builder for chaining.
       */
      public Builder addAllRoleType(
          Iterable<String> values) {
        ensureRoleTypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roleType_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roleType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoleType() {
        roleType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string roleType = 6;</code>
       * @param value The bytes of the roleType to add.
       * @return This builder for chaining.
       */
      public Builder addRoleTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRoleTypeIsMutable();
        roleType_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<Hero> hero_ =
        java.util.Collections.emptyList();
      private void ensureHeroIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          hero_ = new java.util.ArrayList<Hero>(hero_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Hero, Hero.Builder, HeroOrBuilder> heroBuilder_;

      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public java.util.List<Hero> getHeroList() {
        if (heroBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hero_);
        } else {
          return heroBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public int getHeroCount() {
        if (heroBuilder_ == null) {
          return hero_.size();
        } else {
          return heroBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Hero getHero(int index) {
        if (heroBuilder_ == null) {
          return hero_.get(index);
        } else {
          return heroBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Builder setHero(
          int index, Hero value) {
        if (heroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroIsMutable();
          hero_.set(index, value);
          onChanged();
        } else {
          heroBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Builder setHero(
          int index, Hero.Builder builderForValue) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.set(index, builderForValue.build());
          onChanged();
        } else {
          heroBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Builder addHero(Hero value) {
        if (heroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroIsMutable();
          hero_.add(value);
          onChanged();
        } else {
          heroBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Builder addHero(
          int index, Hero value) {
        if (heroBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroIsMutable();
          hero_.add(index, value);
          onChanged();
        } else {
          heroBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Builder addHero(
          Hero.Builder builderForValue) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.add(builderForValue.build());
          onChanged();
        } else {
          heroBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Builder addHero(
          int index, Hero.Builder builderForValue) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.add(index, builderForValue.build());
          onChanged();
        } else {
          heroBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Builder addAllHero(
          Iterable<? extends Hero> values) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hero_);
          onChanged();
        } else {
          heroBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Builder clearHero() {
        if (heroBuilder_ == null) {
          hero_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          heroBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Builder removeHero(int index) {
        if (heroBuilder_ == null) {
          ensureHeroIsMutable();
          hero_.remove(index);
          onChanged();
        } else {
          heroBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Hero.Builder getHeroBuilder(
          int index) {
        return getHeroFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public HeroOrBuilder getHeroOrBuilder(
          int index) {
        if (heroBuilder_ == null) {
          return hero_.get(index);  } else {
          return heroBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public java.util.List<? extends HeroOrBuilder>
           getHeroOrBuilderList() {
        if (heroBuilder_ != null) {
          return heroBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hero_);
        }
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Hero.Builder addHeroBuilder() {
        return getHeroFieldBuilder().addBuilder(
            Hero.getDefaultInstance());
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public Hero.Builder addHeroBuilder(
          int index) {
        return getHeroFieldBuilder().addBuilder(
            index, Hero.getDefaultInstance());
      }
      /**
       * <code>repeated .Hero hero = 7;</code>
       */
      public java.util.List<Hero.Builder>
           getHeroBuilderList() {
        return getHeroFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Hero, Hero.Builder, HeroOrBuilder>
          getHeroFieldBuilder() {
        if (heroBuilder_ == null) {
          heroBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Hero, Hero.Builder, HeroOrBuilder>(
                  hero_,
                  ((bitField0_ & 0x00000040) != 0),
                  getParentForChildren(),
                  isClean());
          hero_ = null;
        }
        return heroBuilder_;
      }

      private com.google.protobuf.Internal.IntList heroLen_ = emptyIntList();
      private void ensureHeroLenIsMutable() {
        if (!((bitField0_ & 0x00000080) != 0)) {
          heroLen_ = mutableCopy(heroLen_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated int32 heroLen = 8;</code>
       * @return A list containing the heroLen.
       */
      public java.util.List<Integer>
          getHeroLenList() {
        return ((bitField0_ & 0x00000080) != 0) ?
                 java.util.Collections.unmodifiableList(heroLen_) : heroLen_;
      }
      /**
       * <code>repeated int32 heroLen = 8;</code>
       * @return The count of heroLen.
       */
      public int getHeroLenCount() {
        return heroLen_.size();
      }
      /**
       * <code>repeated int32 heroLen = 8;</code>
       * @param index The index of the element to return.
       * @return The heroLen at the given index.
       */
      public int getHeroLen(int index) {
        return heroLen_.getInt(index);
      }
      /**
       * <code>repeated int32 heroLen = 8;</code>
       * @param index The index to set the value at.
       * @param value The heroLen to set.
       * @return This builder for chaining.
       */
      public Builder setHeroLen(
          int index, int value) {
        ensureHeroLenIsMutable();
        heroLen_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 heroLen = 8;</code>
       * @param value The heroLen to add.
       * @return This builder for chaining.
       */
      public Builder addHeroLen(int value) {
        ensureHeroLenIsMutable();
        heroLen_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 heroLen = 8;</code>
       * @param values The heroLen to add.
       * @return This builder for chaining.
       */
      public Builder addAllHeroLen(
          Iterable<? extends Integer> values) {
        ensureHeroLenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, heroLen_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 heroLen = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeroLen() {
        heroLen_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <code>optional string message = 9;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional string message = 9;</code>
       * @return The message.
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string message = 9;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 9;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000100);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 9;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000100;
        message_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Role)
    }

    // @@protoc_insertion_point(class_scope:Role)
    private static final Role DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Role();
    }

    public static Role getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Role>
        PARSER = new com.google.protobuf.AbstractParser<Role>() {
      @Override
      public Role parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Role(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Role> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Role> getParserForType() {
      return PARSER;
    }

    @Override
    public Role getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Hero_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Hero_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Role_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Role_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nHero.proto\"d\n\004Hero\022\023\n\006attack\030\001 \001(\003H\000\210\001" +
      "\001\022\024\n\007defense\030\002 \001(\003H\001\210\001\001\022\021\n\004life\030\003 \001(\003H\002\210" +
      "\001\001B\t\n\007_attackB\n\n\010_defenseB\007\n\005_life\"\255\001\n\004R" +
      "ole\022\n\n\002id\030\001 \003(\005\022\013\n\003uid\030\002 \003(\005\022\020\n\010serverId" +
      "\030\003 \003(\005\022\016\n\006roleId\030\004 \003(\005\022\020\n\010roleName\030\005 \003(\t" +
      "\022\020\n\010roleType\030\006 \003(\t\022\023\n\004hero\030\007 \003(\0132\005.Hero\022" +
      "\017\n\007heroLen\030\010 \003(\005\022\024\n\007message\030\t \001(\tH\000\210\001\001B\n" +
      "\n\010_messageB\031\n\014yxl.day5.dtoB\tHeroProtob\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Hero_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Hero_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Hero_descriptor,
        new String[] { "Attack", "Defense", "Life", "Attack", "Defense", "Life", });
    internal_static_Role_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Role_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Role_descriptor,
        new String[] { "Id", "Uid", "ServerId", "RoleId", "RoleName", "RoleType", "Hero", "HeroLen", "Message", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
