// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocl.proto

package yxl.day4.dto;

public final class ProtoclProto {
  private ProtoclProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ProtoclType}
   */
  public enum ProtoclType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *空
     * </pre>
     *
     * <code>C2S_None = 0;</code>
     */
    C2S_None(0),
    /**
     * <pre>
     *拾取
     * </pre>
     *
     * <code>C2S_Pick = 1;</code>
     */
    C2S_Pick(1),
    /**
     * <pre>
     *收取返回
     * </pre>
     *
     * <code>S2C_Pick = 2;</code>
     */
    S2C_Pick(2),
    /**
     * <pre>
     *扔掉
     * </pre>
     *
     * <code>C2S_Throw = 3;</code>
     */
    C2S_Throw(3),
    /**
     * <pre>
     *扔掉返回
     * </pre>
     *
     * <code>S2C_Throw = 4;</code>
     */
    S2C_Throw(4),
    /**
     * <pre>
     *销毁
     * </pre>
     *
     * <code>C2S_Destroy = 5;</code>
     */
    C2S_Destroy(5),
    /**
     * <pre>
     *销毁返回
     * </pre>
     *
     * <code>S2C_Destroy = 6;</code>
     */
    S2C_Destroy(6),
    /**
     * <pre>
     *给别人
     * </pre>
     *
     * <code>C2S_Give = 7;</code>
     */
    C2S_Give(7),
    /**
     * <pre>
     *给别人返回
     * </pre>
     *
     * <code>S2C_Give = 8;</code>
     */
    S2C_Give(8),
    /**
     * <pre>
     *获取道具掉落信息
     * </pre>
     *
     * <code>C2S_Obtain = 9;</code>
     */
    C2S_Obtain(9),
    /**
     * <pre>
     *掉落信息返回
     * </pre>
     *
     * <code>S2C_Obtain = 10;</code>
     */
    S2C_Obtain(10),
    /**
     * <pre>
     *展示我的物品
     * </pre>
     *
     * <code>C2S_Show = 11;</code>
     */
    C2S_Show(11),
    /**
     * <pre>
     *展示我的物品返回
     * </pre>
     *
     * <code>S2C_Show = 12;</code>
     */
    S2C_Show(12),
    /**
     * <pre>
     *展示未被拾取的装备
     * </pre>
     *
     * <code>C2S_ShowNoPick = 13;</code>
     */
    C2S_ShowNoPick(13),
    /**
     * <pre>
     *返回未被拾取等装备
     * </pre>
     *
     * <code>S2C_ShowNoPick = 14;</code>
     */
    S2C_ShowNoPick(14),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *空
     * </pre>
     *
     * <code>C2S_None = 0;</code>
     */
    public static final int C2S_None_VALUE = 0;
    /**
     * <pre>
     *拾取
     * </pre>
     *
     * <code>C2S_Pick = 1;</code>
     */
    public static final int C2S_Pick_VALUE = 1;
    /**
     * <pre>
     *收取返回
     * </pre>
     *
     * <code>S2C_Pick = 2;</code>
     */
    public static final int S2C_Pick_VALUE = 2;
    /**
     * <pre>
     *扔掉
     * </pre>
     *
     * <code>C2S_Throw = 3;</code>
     */
    public static final int C2S_Throw_VALUE = 3;
    /**
     * <pre>
     *扔掉返回
     * </pre>
     *
     * <code>S2C_Throw = 4;</code>
     */
    public static final int S2C_Throw_VALUE = 4;
    /**
     * <pre>
     *销毁
     * </pre>
     *
     * <code>C2S_Destroy = 5;</code>
     */
    public static final int C2S_Destroy_VALUE = 5;
    /**
     * <pre>
     *销毁返回
     * </pre>
     *
     * <code>S2C_Destroy = 6;</code>
     */
    public static final int S2C_Destroy_VALUE = 6;
    /**
     * <pre>
     *给别人
     * </pre>
     *
     * <code>C2S_Give = 7;</code>
     */
    public static final int C2S_Give_VALUE = 7;
    /**
     * <pre>
     *给别人返回
     * </pre>
     *
     * <code>S2C_Give = 8;</code>
     */
    public static final int S2C_Give_VALUE = 8;
    /**
     * <pre>
     *获取道具掉落信息
     * </pre>
     *
     * <code>C2S_Obtain = 9;</code>
     */
    public static final int C2S_Obtain_VALUE = 9;
    /**
     * <pre>
     *掉落信息返回
     * </pre>
     *
     * <code>S2C_Obtain = 10;</code>
     */
    public static final int S2C_Obtain_VALUE = 10;
    /**
     * <pre>
     *展示我的物品
     * </pre>
     *
     * <code>C2S_Show = 11;</code>
     */
    public static final int C2S_Show_VALUE = 11;
    /**
     * <pre>
     *展示我的物品返回
     * </pre>
     *
     * <code>S2C_Show = 12;</code>
     */
    public static final int S2C_Show_VALUE = 12;
    /**
     * <pre>
     *展示未被拾取的装备
     * </pre>
     *
     * <code>C2S_ShowNoPick = 13;</code>
     */
    public static final int C2S_ShowNoPick_VALUE = 13;
    /**
     * <pre>
     *返回未被拾取等装备
     * </pre>
     *
     * <code>S2C_ShowNoPick = 14;</code>
     */
    public static final int S2C_ShowNoPick_VALUE = 14;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ProtoclType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ProtoclType forNumber(int value) {
      switch (value) {
        case 0: return C2S_None;
        case 1: return C2S_Pick;
        case 2: return S2C_Pick;
        case 3: return C2S_Throw;
        case 4: return S2C_Throw;
        case 5: return C2S_Destroy;
        case 6: return S2C_Destroy;
        case 7: return C2S_Give;
        case 8: return S2C_Give;
        case 9: return C2S_Obtain;
        case 10: return S2C_Obtain;
        case 11: return C2S_Show;
        case 12: return S2C_Show;
        case 13: return C2S_ShowNoPick;
        case 14: return S2C_ShowNoPick;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtoclType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtoclType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtoclType>() {
            public ProtoclType findValueByNumber(int number) {
              return ProtoclType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ProtoclProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProtoclType[] VALUES = values();

    public static ProtoclType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtoclType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoclType)
  }

  public interface protoclOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *协议类型
     * </pre>
     *
     * <code>.ProtoclType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     *协议类型
     * </pre>
     *
     * <code>.ProtoclType type = 1;</code>
     * @return The type.
     */
    ProtoclType getType();

    /**
     * <pre>
     *物品id
     * </pre>
     *
     * <code>optional int32 id = 2;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <pre>
     *物品id
     * </pre>
     *
     * <code>optional int32 id = 2;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional int32 uid = 3;</code>
     * @return Whether the uid field is set.
     */
    boolean hasUid();
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional int32 uid = 3;</code>
     * @return The uid.
     */
    int getUid();

    /**
     * <pre>
     *返回状态
     * </pre>
     *
     * <code>optional bool status = 4;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <pre>
     *返回状态
     * </pre>
     *
     * <code>optional bool status = 4;</code>
     * @return The status.
     */
    boolean getStatus();

    /**
     * <pre>
     *数据 道具数据或者错误信息。
     * </pre>
     *
     * <code>optional string proJson = 5;</code>
     * @return Whether the proJson field is set.
     */
    boolean hasProJson();
    /**
     * <pre>
     *数据 道具数据或者错误信息。
     * </pre>
     *
     * <code>optional string proJson = 5;</code>
     * @return The proJson.
     */
    String getProJson();
    /**
     * <pre>
     *数据 道具数据或者错误信息。
     * </pre>
     *
     * <code>optional string proJson = 5;</code>
     * @return The bytes for proJson.
     */
    com.google.protobuf.ByteString
        getProJsonBytes();

    /**
     * <pre>
     *给予用户id
     * </pre>
     *
     * <code>optional int32 guid = 6;</code>
     * @return Whether the guid field is set.
     */
    boolean hasGuid();
    /**
     * <pre>
     *给予用户id
     * </pre>
     *
     * <code>optional int32 guid = 6;</code>
     * @return The guid.
     */
    int getGuid();
  }
  /**
   * Protobuf type {@code protocl}
   */
  public static final class protocl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocl)
      protoclOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use protocl.newBuilder() to construct.
    private protocl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private protocl() {
      type_ = 0;
      proJson_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new protocl();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private protocl(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              uid_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              status_ = input.readBool();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              proJson_ = s;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              guid_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoclProto.internal_static_protocl_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoclProto.internal_static_protocl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocl.class, Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *协议类型
     * </pre>
     *
     * <code>.ProtoclType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *协议类型
     * </pre>
     *
     * <code>.ProtoclType type = 1;</code>
     * @return The type.
     */
    @Override public ProtoclType getType() {
      @SuppressWarnings("deprecation")
      ProtoclType result = ProtoclType.valueOf(type_);
      return result == null ? ProtoclType.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <pre>
     *物品id
     * </pre>
     *
     * <code>optional int32 id = 2;</code>
     * @return Whether the id field is set.
     */
    @Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *物品id
     * </pre>
     *
     * <code>optional int32 id = 2;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }

    public static final int UID_FIELD_NUMBER = 3;
    private int uid_;
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional int32 uid = 3;</code>
     * @return Whether the uid field is set.
     */
    @Override
    public boolean hasUid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>optional int32 uid = 3;</code>
     * @return The uid.
     */
    @Override
    public int getUid() {
      return uid_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private boolean status_;
    /**
     * <pre>
     *返回状态
     * </pre>
     *
     * <code>optional bool status = 4;</code>
     * @return Whether the status field is set.
     */
    @Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *返回状态
     * </pre>
     *
     * <code>optional bool status = 4;</code>
     * @return The status.
     */
    @Override
    public boolean getStatus() {
      return status_;
    }

    public static final int PROJSON_FIELD_NUMBER = 5;
    private volatile Object proJson_;
    /**
     * <pre>
     *数据 道具数据或者错误信息。
     * </pre>
     *
     * <code>optional string proJson = 5;</code>
     * @return Whether the proJson field is set.
     */
    @Override
    public boolean hasProJson() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *数据 道具数据或者错误信息。
     * </pre>
     *
     * <code>optional string proJson = 5;</code>
     * @return The proJson.
     */
    @Override
    public String getProJson() {
      Object ref = proJson_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        proJson_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *数据 道具数据或者错误信息。
     * </pre>
     *
     * <code>optional string proJson = 5;</code>
     * @return The bytes for proJson.
     */
    @Override
    public com.google.protobuf.ByteString
        getProJsonBytes() {
      Object ref = proJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        proJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GUID_FIELD_NUMBER = 6;
    private int guid_;
    /**
     * <pre>
     *给予用户id
     * </pre>
     *
     * <code>optional int32 guid = 6;</code>
     * @return Whether the guid field is set.
     */
    @Override
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *给予用户id
     * </pre>
     *
     * <code>optional int32 guid = 6;</code>
     * @return The guid.
     */
    @Override
    public int getGuid() {
      return guid_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != ProtoclType.C2S_None.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, uid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(4, status_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, proJson_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(6, guid_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != ProtoclType.C2S_None.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, uid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, status_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, proJson_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, guid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocl)) {
        return super.equals(obj);
      }
      protocl other = (protocl) obj;

      if (type_ != other.type_) return false;
      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasUid() != other.hasUid()) return false;
      if (hasUid()) {
        if (getUid()
            != other.getUid()) return false;
      }
      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (getStatus()
            != other.getStatus()) return false;
      }
      if (hasProJson() != other.hasProJson()) return false;
      if (hasProJson()) {
        if (!getProJson()
            .equals(other.getProJson())) return false;
      }
      if (hasGuid() != other.hasGuid()) return false;
      if (hasGuid()) {
        if (getGuid()
            != other.getGuid()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasUid()) {
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getStatus());
      }
      if (hasProJson()) {
        hash = (37 * hash) + PROJSON_FIELD_NUMBER;
        hash = (53 * hash) + getProJson().hashCode();
      }
      if (hasGuid()) {
        hash = (37 * hash) + GUID_FIELD_NUMBER;
        hash = (53 * hash) + getGuid();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocl parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocl parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocl)
        protoclOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoclProto.internal_static_protocl_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoclProto.internal_static_protocl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocl.class, Builder.class);
      }

      // Construct using yxl.day4.dto.ProtoclProto.protocl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        proJson_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        guid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoclProto.internal_static_protocl_descriptor;
      }

      @Override
      public protocl getDefaultInstanceForType() {
        return protocl.getDefaultInstance();
      }

      @Override
      public protocl build() {
        protocl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public protocl buildPartial() {
        protocl result = new protocl(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.uid_ = uid_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.status_ = status_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.proJson_ = proJson_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.guid_ = guid_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocl) {
          return mergeFrom((protocl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocl other) {
        if (other == protocl.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasProJson()) {
          bitField0_ |= 0x00000008;
          proJson_ = other.proJson_;
          onChanged();
        }
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocl parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocl) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <pre>
       *协议类型
       * </pre>
       *
       * <code>.ProtoclType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *协议类型
       * </pre>
       *
       * <code>.ProtoclType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议类型
       * </pre>
       *
       * <code>.ProtoclType type = 1;</code>
       * @return The type.
       */
      @Override
      public ProtoclType getType() {
        @SuppressWarnings("deprecation")
        ProtoclType result = ProtoclType.valueOf(type_);
        return result == null ? ProtoclType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *协议类型
       * </pre>
       *
       * <code>.ProtoclType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(ProtoclType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议类型
       * </pre>
       *
       * <code>.ProtoclType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       *物品id
       * </pre>
       *
       * <code>optional int32 id = 2;</code>
       * @return Whether the id field is set.
       */
      @Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *物品id
       * </pre>
       *
       * <code>optional int32 id = 2;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *物品id
       * </pre>
       *
       * <code>optional int32 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *物品id
       * </pre>
       *
       * <code>optional int32 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional int32 uid = 3;</code>
       * @return Whether the uid field is set.
       */
      @Override
      public boolean hasUid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional int32 uid = 3;</code>
       * @return The uid.
       */
      @Override
      public int getUid() {
        return uid_;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional int32 uid = 3;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000002;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>optional int32 uid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = 0;
        onChanged();
        return this;
      }

      private boolean status_ ;
      /**
       * <pre>
       *返回状态
       * </pre>
       *
       * <code>optional bool status = 4;</code>
       * @return Whether the status field is set.
       */
      @Override
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *返回状态
       * </pre>
       *
       * <code>optional bool status = 4;</code>
       * @return The status.
       */
      @Override
      public boolean getStatus() {
        return status_;
      }
      /**
       * <pre>
       *返回状态
       * </pre>
       *
       * <code>optional bool status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(boolean value) {
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *返回状态
       * </pre>
       *
       * <code>optional bool status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = false;
        onChanged();
        return this;
      }

      private Object proJson_ = "";
      /**
       * <pre>
       *数据 道具数据或者错误信息。
       * </pre>
       *
       * <code>optional string proJson = 5;</code>
       * @return Whether the proJson field is set.
       */
      public boolean hasProJson() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *数据 道具数据或者错误信息。
       * </pre>
       *
       * <code>optional string proJson = 5;</code>
       * @return The proJson.
       */
      public String getProJson() {
        Object ref = proJson_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          proJson_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *数据 道具数据或者错误信息。
       * </pre>
       *
       * <code>optional string proJson = 5;</code>
       * @return The bytes for proJson.
       */
      public com.google.protobuf.ByteString
          getProJsonBytes() {
        Object ref = proJson_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          proJson_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *数据 道具数据或者错误信息。
       * </pre>
       *
       * <code>optional string proJson = 5;</code>
       * @param value The proJson to set.
       * @return This builder for chaining.
       */
      public Builder setProJson(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        proJson_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据 道具数据或者错误信息。
       * </pre>
       *
       * <code>optional string proJson = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearProJson() {
        bitField0_ = (bitField0_ & ~0x00000008);
        proJson_ = getDefaultInstance().getProJson();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据 道具数据或者错误信息。
       * </pre>
       *
       * <code>optional string proJson = 5;</code>
       * @param value The bytes for proJson to set.
       * @return This builder for chaining.
       */
      public Builder setProJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000008;
        proJson_ = value;
        onChanged();
        return this;
      }

      private int guid_ ;
      /**
       * <pre>
       *给予用户id
       * </pre>
       *
       * <code>optional int32 guid = 6;</code>
       * @return Whether the guid field is set.
       */
      @Override
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *给予用户id
       * </pre>
       *
       * <code>optional int32 guid = 6;</code>
       * @return The guid.
       */
      @Override
      public int getGuid() {
        return guid_;
      }
      /**
       * <pre>
       *给予用户id
       * </pre>
       *
       * <code>optional int32 guid = 6;</code>
       * @param value The guid to set.
       * @return This builder for chaining.
       */
      public Builder setGuid(int value) {
        bitField0_ |= 0x00000010;
        guid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *给予用户id
       * </pre>
       *
       * <code>optional int32 guid = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        guid_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocl)
    }

    // @@protoc_insertion_point(class_scope:protocl)
    private static final protocl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocl();
    }

    public static protocl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<protocl>
        PARSER = new com.google.protobuf.AbstractParser<protocl>() {
      @Override
      public protocl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new protocl(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<protocl> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<protocl> getParserForType() {
      return PARSER;
    }

    @Override
    public protocl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocl_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rprotocl.proto\"\265\001\n\007protocl\022\032\n\004type\030\001 \001(" +
      "\0162\014.ProtoclType\022\017\n\002id\030\002 \001(\005H\000\210\001\001\022\020\n\003uid\030" +
      "\003 \001(\005H\001\210\001\001\022\023\n\006status\030\004 \001(\010H\002\210\001\001\022\024\n\007proJs" +
      "on\030\005 \001(\tH\003\210\001\001\022\021\n\004guid\030\006 \001(\005H\004\210\001\001B\005\n\003_idB" +
      "\006\n\004_uidB\t\n\007_statusB\n\n\010_proJsonB\007\n\005_guid*" +
      "\367\001\n\013ProtoclType\022\014\n\010C2S_None\020\000\022\014\n\010C2S_Pic" +
      "k\020\001\022\014\n\010S2C_Pick\020\002\022\r\n\tC2S_Throw\020\003\022\r\n\tS2C_" +
      "Throw\020\004\022\017\n\013C2S_Destroy\020\005\022\017\n\013S2C_Destroy\020" +
      "\006\022\014\n\010C2S_Give\020\007\022\014\n\010S2C_Give\020\010\022\016\n\nC2S_Obt" +
      "ain\020\t\022\016\n\nS2C_Obtain\020\n\022\014\n\010C2S_Show\020\013\022\014\n\010S" +
      "2C_Show\020\014\022\022\n\016C2S_ShowNoPick\020\r\022\022\n\016S2C_Sho" +
      "wNoPick\020\016B\034\n\014yxl.day4.dtoB\014ProtoclProtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocl_descriptor,
        new String[] { "Type", "Id", "Uid", "Status", "ProJson", "Guid", "Id", "Uid", "Status", "ProJson", "Guid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
